#!/usr/bin/python
import os

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 
import morepath
import kso_site
import wfront
import wsgi_fileserver

fileserver_app = wsgi_fileserver.WSGIFileServerApplication(
    root_path=os.path.join(os.environ['OPENSHIFT_DATA_DIR'], 'repository')
)

mapping = [
    ('www.kagesenshi.org', kso_site.app),
    ('repo.koslab.org', fileserver_app)
]

config = morepath.setup()
config.scan(package=kso_site)
config.commit()

application = wfront.route(mapping, default=kso_site.app)

if __name__=='__main__':
    application.run()
