#!/usr/bin/python
import os

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 
import morepath

config = morepath.setup()
config.scan()
config.commit()
application = morepath.App()

@application.path(path='')
class Root(object):
    pass

@application.html(model=Root)
def hello_root(self, request):
    return u'<h1>Hello World</h1>'
